  - name: variables to print #play level task , it apply gor all 
    hosts: web
    vars:
      COURSE: "Devops with aws"
      DURATION: "120HRS"
      TIMEINGS: "7:15 -8:45 am ist"
      TRAINER: "sivakumar reddy M "
    tasks: 
    - name: print the information
      ansible.builtin.debug:
       msg: "HI, I am learning {{COURSE}}, Duration is: {{DURATION}}, Timeings is: {{TIMEINGS}}, Trainer: {{TRAINER}}"

    - name: print the information again
      vasrs: 
       COURSE: "Ansible" # it is task level , it only apply for wanted task level 
      ansible.builtin.debug:
        msg: "HI, I am learning {{COURSE}}, Duration is: {{DURATION}}, Timeings is: {{TIMEINGS}}, Trainer: {{TRAINER}}"
    
    - name: print the information again 2
      ansible.builtin.debug:
        msg: "HI, I am learning {{COURSE}}, Duration is: {{DURATION}}, Timeings is: {{TIMEINGS}}, Trainer: {{TRAINER}}"  
