- name: print the variables 
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the course information 
    asible.builtin.debug:
      msg: "HI Iam learning {{COURSE}}, Duration is: {{DURATIONS}}, Timeings is: {{TIMEINGS}}, Trainer: {{TRAINER}}"

  