- name: print the vars files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the course information 
    ansible.builtin.debug:
      msg: "HI Iam learning {{COURSE}}, Duration is: {{DURATIONS}}, Timeings is: {{TIMEINGS}}, Trainer: {{TRAINER}}"

  