  
- name: variables to print
  hosts: web
  vars:
      COURSE: "DevOps with AWS from PLAY level"
      DURATION: "120HRS"
      TRAINER: "SIVA"
  vars_files:
  - vars.yaml
  vars_prompt:
    - name: COURSE
      prompt: Please enter the course name
      private: false # not confidential    

  tasks:
    - name: print the information
      ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}"